events {}
http {
    server {
        listen 80;

        # Patient frontend → port 3000
        location / {
            proxy_pass http://frontend:80;
        }

        # Admin frontend → subdomain or /admin path
        location /admin {
            proxy_pass http://admin:80;
        }

        # Backend API
        location /api {
            proxy_pass http://backend:4000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}